---
  version: '3.5'

  x-config:
    &default-config
    container_name: wma-spring-boot-base
    ports:
      - "8443:8443"
    secrets:
      - source: tomcat_ssl_chain
        target: /home/spring/tomcat-wildcard-ssl.chain
      - source: tomcat_ssl_crt
        target: /home/spring/tomcat-wildcard-ssl.crt
      - source: tomcat_ssl_key
        target: /home/spring/tomcat-wildcard-ssl.key
    env_file:
      - config.env
      - secrets.env

  secrets:
    tomcat_ssl_chain:
      file: ./certificates/tomcat-wildcard.chain
    tomcat_ssl_crt:
      file: ./certificates/tomcat-wildcard.crt
    tomcat_ssl_key:
      file: ./certificates/tomcat-wildcard.key

  services:
    8-jre-slim:
      build:
        context: .
        args:
          OPENJDK_TAG: '8u181-jre-slim'
      image: wma-spring-boot-base:8-jre-slim-latest
      << : *default-config

    10-jre-slim:
      build:
        context: .
        args:
          OPENJDK_TAG: '10.0.2-13-jre-slim'
          DEFAULT_JAVA_OPTIONS: "-Xmx300M -server -Djava.security.egd=file:/dev/./urandom"
      image: wma-spring-boot-base:10-jre-slim-latest
      << : *default-config

    latest:
      build:
        context: .
        args:
          OPENJDK_TAG: '8u181-jre-slim'
      image: wma-spring-boot-base:latest
      << : *default-config
