---
  version: '3.5'

  x-config:
    &default-config
    ports:
      - "443:443"
    secrets:
      - source: tomcat_ssl_crt
        target: /home/spring/tomcat-wildcard-ssl.crt
      - source: tomcat_ssl_key
        target: /home/spring/tomcat-wildcard-ssl.key
    env_file:
      - config.env
      - secrets.env

  secrets:
    tomcat_ssl_crt:
      file: ./certificates/tomcat/tomcat-wildcard-dev.crt
    tomcat_ssl_key:
      file: ./certificates/tomcat/tomcat-wildcard-dev.key

  services:
    8-jre-slim:
      build:
        context: .
        args:
          OPENJDK_TAG: '8-jre-slim'
      image: wma-spring-boot-base:8-jre-slim
      << : *default-config

    10.0.1-jre-slim:
      build:
        context: .
        args:
          OPENJDK_TAG: '10.0.1-jre-slim'
      image: wma-spring-boot-base:10.0.1-jre-slim
      << : *default-config

    latest:
      build:
        context: .
        args:
          OPENJDK_TAG: '10.0.1-jre-slim'
      image: wma-spring-boot-base:latest
      << : *default-config
